### ISSUE TITLE
needle v2.4.0 issue

### ISSUE THREAD

**Issue by bestpika** [libxmljs/libxmljs-dom#12]
If use needle@2.4.0 will get the error.

```
Error: Invalid property for defaults:compressed
    at Function.module.exports.defaults (D:\tmp\n0use-api-heroku-nodejs\node_modules\needle\lib\needle.js:776:13)
    at Object.<anonymous> (D:\tmp\n0use-api-heroku-nodejs\node_modules\libxmljs-dom\lib\HttpRequest.js:5:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\tmp\n0use-api-heroku-nodejs\node_modules\libxmljs-dom\lib\Window.js:8:22)
```

I try to change needle to v2.3.0 and work fine.

**Comment by bestpika** [comment]
Use npm/pnpm install needle@2.3.0 and the bug will go.

**Comment by james58899** [comment]
https://github.com/libxmljs/libxmljs-dom/blob/5e91abeb04e62596fda8610e728e333a7f06fd02/package.json#L23

Maybe add `<=2.3.0`
